targets:
  $default:
    sources:
      - lib/**
      - test/**
      - integration_test/**
      - $package$
    builders:
      bdd_widget_test|featureBuilder:
        options:
          addHooks: true
#          hookFolderName: /test/acceptance_test/hook/
#          stepFolderName: acceptance_test/step